#!/bin/bash

set -e

flatpak install com.github.libresprite.LibreSprite

flatpak install org.blender.Blender
cd ~/Downloads
wget https://github.com/Radivarig/UvSquares/archive/master.zip -O UvSquares.zip

sudo apt install -y krita
sudo apt install -y gimp
sudo apt install -y inkscape
sudo apt install -y audacity
sudo apt install -y lmms
sudo apt install -y obs-studio
