#!/bin/bash

set -e

sudo apt install -y gnome-shell-extensions
sudo apt install -y ubuntu-restricted-extras
sudo apt install -y hardinfo
sudo apt install -y mesa-utils
sudo apt install -y vlc
sudo apt install -y rhythembox
sudo apt install -y epiphany-browser
sudo apt install -y cheese
