#!/bin/bash -i

set -e

curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
source ~/.bashrc
nvm install node

echo "Add the following layers to .spacemacs: javascript typescript"
echo "Do not select eslint as your backend"
