#!/bin/bash

sudo apt install -y default-jre
sudo apt install -y texlive-full

cd ~/.emacs.d/private
curl -L https://raw.githubusercontent.com/languagetool-org/languagetool/master/install.sh | bash

echo "Add the following layer to .spacemacs: languagetool"
echo "Configure language tool with languagetool.jar"
